server:
  port: 8182

domain:
  name: order

sequence-nextval: nextval(event_seq)

logging:
  level:
    com.amazonaws.xray: DEBUG
    org.springframework.boot: INFO
    org.springframework.core : INFO
    
spring:
  application:
    name: awesome-order-service
  config:
    import: 
    - file:./config/application-prd.yml
              
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"