zuul:
  routes:
    js-account-service:
      service-id: js-account-service
      url: http://account:8180
      path: /account/**
    js-cart-service:
      service-id: js-cart-service
      url: http://cart:8181
      path: /cart/**
    js-order-service:
      service-id: js-order-service
      url: http://order:8182
      path: /order/**
    js-payment-service:
      service-id: js-payment-service
      url: http://payment:8183
      path: /payment/**
    js-product-service:
      service-id: js-product-service
      url: http://product:8184
      path: /product/**
