mybatis:
  config-location: mybatis-config-mariadb.xml

spring:

  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb-shop.shop-infra/payments?characterEncoding=UTF-8
    username: root
    password: skcc
    platform: mariadb
    initialization-mode: always
    # continue-on-error: true

  rabbitmq:
    addresses: rabbitmq.shop-infra
    username: labs
    password: awesome-rabbitmq
  cloud:
    stream:
      bindings:
        paymentOutput:
          destination: paymentTopic
          content-type: application/json
      rabbit:
        bindings:
          paymentOutput:
            producer:
              routing-key-expression: headers['routeTo']